name: mot
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip>=20.1
  - pydantic>=1.6
  - pyyaml>=5.3
  - pytorch=1.8
  - torchvision=0.9
  - cudatoolkit=10.2
  - pandas>=1.1
  - scikit-learn>=0.24
  - matplotlib
  - seaborn
  - pip:
      - opencv-python>=4.5
      - progress
      - lap
      - openpyxl
      - yacs
      - numba
      - motmetrics
      - easydict
